title: "Henry Tao"
description: ""
about: ""
location: "New York City, NY"
email: htaox@hotmail.com
baseurl: ""
url: "https://once-ler.github.io/"
twitter_username: htaox
github_username:  once-ler

# google analytics tracking code, please change the value
# g_analytics: "UA-72004048-3"

# language settings
isolang: eng
close_btn: "Ausblenden"
home_btn: "Startseite"
projects_btn: "Projekte"
posts_btn: "Posts"
imprint_btn: "Impressum"
name_badge: "Ein Artikel von"
rss_badge: "Feed abbonieren!"

# build settings
markdown: kramdown

# exclude files
exclude:
  - LICENSE
  - README.md
